var leftNav = {}; // left nav namespace

leftNav.control = { // methods for ui elements
	addNewRow: function(event, t) {
		// addNewRow will add a new empty row to the current DataRow document
		// new rows are generated by the generateUniqueRow helper
		event.preventDefault();
		// stub out a new blank row object
		var newRow = GlobalValues.defaultRowData;
		// add the working documents id to the new empty object
		newRow.associatedDocument = Session.get('document');
		// add the new object to RowData
		RowData.insert(newRow);
	},
	addNewSection: function(event, t) {
		event.preventDefault();
		console.log('Build a new section');
	}
};

$(document).ready(function() {
	Template.left_nav.events({ // assigning events to the template
		'click #btn_add_item': leftNav.control.addNewRow,
		'click #btn_create_section': leftNav.control.addNewSection
	});
});